# Company Standard Configuration
# This configuration represents a standard setup for enterprise projects

name: company_standard
version: 1.0.0
author: Engineering Team
description: Standard configuration for enterprise Flutter projects with best practices

defaults:
  state_management: riverpod
  platforms:
    - mobile
    - web
  ci_provider: github
  include_theme: true
  include_localization: true
  include_env: true
  include_api: true
  include_tests: true

required_packages:
  - dio
  - shared_preferences
  - flutter_secure_storage
  - cached_network_image
  - intl
  - go_router

code_style:
  line_length: 80
  prefer_const: true

architecture:
  naming_convention: snake_case

metadata:
  organization: "My Company Inc"
  team: "Mobile Development"
  support_email: "mobile-dev@company.com"
  documentation_url: "https://wiki.company.com/mobile-standards"
