# Enterprise Template Configuration
# Comprehensive configuration for large-scale enterprise applications

name: enterprise_template
version: 1.0.0
author: Enterprise Architecture Team
description: Full-featured configuration for enterprise-grade applications with all bells and whistles

defaults:
  state_management: bloc
  platforms:
    - mobile
    - web
    - desktop
  ci_provider: azure
  include_theme: true
  include_localization: true
  include_env: true
  include_api: true
  include_tests: true

required_packages:
  - dio
  - retrofit
  - freezed
  - injectable
  - get_it
  - shared_preferences
  - flutter_secure_storage
  - hive
  - cached_network_image
  - intl
  - go_router
  - logger
  - sentry_flutter
  - firebase_core
  - firebase_analytics
  - firebase_crashlytics

code_style:
  line_length: 80
  prefer_const: true

architecture:
  naming_convention: snake_case

metadata:
  organization: "Enterprise Corp"
  compliance: "SOC 2, GDPR, HIPAA"
  security_level: "High"
  code_review_required: true
  documentation_standard: "JSDoc"
  version_control: "Trunk-based development"
